version: "3.9"

services:
  db:
    container_name: chat-group-db
    image: postgres
    environment:
      - POSTGRES_DB=chat-group-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=chupapi1234
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  client:
    container_name: chat-group-client
    image: cg-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    container_name: chat-group-server
    image: cg-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/chat-group-db
      - DB_USERNAME=root
      - DB_PASSWORD=chupapi1234
    depends_on:
      - db

volumes:
  postgres:
