version: "3.9"

services:
  db:
    container_name: chat-group-db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=chat-group-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=chupapi1234
      - MYSQL_ROOT_PASSWORD=chupapi1234
    ports:
      - "3306:3306"

  client:
    container_name: chat-group-client
    image: cg-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    container_name: chat-group-server
    image: cg-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/chat-group-db
      - DB_USERNAME=root
      - DB_PASSWORD=chupapi1234
    depends_on:
      - db
