ALTER TABLE chat_user
    ADD COLUMN role VARCHAR(10) DEFAULT 'MEMBER';

ALTER TABLE chat
    ADD COLUMN title VARCHAR(50) NOT NULL,
    ADD COLUMN owner_id BIGINT,
    ADD COLUMN description VARCHAR(255) NOT NULL;