spring:
  profile.active: dev, test, prod
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/chat-group-db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:chupapi1234}
    driverClassName: com.mysql.cj.jdbc.Driver

  jackson:
    serialization:
      fail-on-empty-beans: false

  # For Development
  jpa:
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Server error properties
server:
  error:
    include-stacktrace: never

#env
api:
  jwt:
    secret: ${JWT_SECRET:Hola_chupapis1234Hola_chupapis1234Hola_chupapis1234}
    expiration-in-ms: 86400000
  cors.origin: ${CLIENT_URL:http://localhost:3000}